<a href="https://colab.research.google.com/github/Akshagajja/Data-science-tutorial/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data1={'Name':['jennie','princi','jimin','jhope'],
        'Age':[27,24,22,32],
        'Address':['mumbai','hyderabad','korea','karnataka'],
        'Qualification':['Msc','MA','MCA','phd'],
        'salary':[1000,2000,3000,4000]}
data2=data1={'Name':['jennie','lisa','suge','felix'],
        'Age':[27,14,12,52],
        'Address':['mumbai','hyderabad','korea','karnataka'],
        'Qualification':['B tech','B com','BSc','B.A'],
        'salary':[1000,2000,3000,4000]}
#to convert the dictionary into dataframe
df=pd.DataFrame(data1,index=[0,1,2,3])
#covert dictionary into dataframe
df1=pd.DataFrame(data2,index=[2,3,6,7])
print(df,"\n\n",df1)
#using a .concat() method
res1=pd.concat([df,df1])
res1
res2=pd.concat([df,df1],axis=1,join='inner')
res2

     Name  Age    Address Qualification  salary
0  jennie   27     mumbai        B tech    1000
1    lisa   14  hyderabad         B com    2000
2    suge   12      korea           BSc    3000
3   felix   52  karnataka           B.A    4000

      Name  Age    Address Qualification  salary
2  jennie   27     mumbai        B tech    1000
3    lisa   14  hyderabad         B com    2000
6    suge   12      korea           BSc    3000
7   felix   52  karnataka           B.A    4000

,Name,Age,Address,Qualification,salary,Name,Age,Address,Qualification,salary
2,suge,12,korea,BSc,3000,jennie,27,mumbai,B tech,1000
3,felix,52,karnataka,B.A,4000,lisa,14,hyderabad,B com,2000

In [3]:
import pandas as pd
data1={'Name':['jennie','princi','jimin','jhope'],
        'Age':[27,24,22,32],
        'Address':['mumbai','hyderabad','korea','karnataka'],
        'Qualification':['Msc','MA','MCA','phd'],
        'salary':[1000,2000,3000,4000]}
data2=data1={'Name':['jennie','lisa','suge','felix'],
        'Age':[27,14,12,52],
        'Address':['mumbai','hyderabad','korea','karnataka'],
        'Qualification':['B tech','B com','BSc','B.A'],
        'salary':[1000,2000,3000,4000]}
df=pd.DataFrame(data1,index=[0,1,2,3])
df1=pd.DataFrame(data2,index=[2,3,6,7])
print(df,"\n\n",df1)
#using ignore index
res=pd.concat([df,df1],ignore_index=True)
res

     Name  Age    Address Qualification  salary
0  jennie   27     mumbai        B tech    1000
1    lisa   14  hyderabad         B com    2000
2    suge   12      korea           BSc    3000
3   felix   52  karnataka           B.A    4000

      Name  Age    Address Qualification  salary
2  jennie   27     mumbai        B tech    1000
3    lisa   14  hyderabad         B com    2000
6    suge   12      korea           BSc    3000
7   felix   52  karnataka           B.A    4000

     Name  Age    Address Qualification  salary
0  jennie   27     mumbai        B tech    1000
1    lisa   14  hyderabad         B com    2000
2    suge   12      korea           BSc    3000
3   felix   52  karnataka           B.A    4000
4  jennie   27     mumbai        B tech    1000
5    lisa   14  hyderabad         B com    2000
6    suge   12      korea           BSc    3000
7   felix   52  karnataka           B.A    4000